### PR TITLE
Use the official rollup plugin in Readme

### PR DESCRIPTION
**Pull request by posva**

### CODE REVIEW

**Comment by lyonlai** [comment]
Hi @posva, I've just quickly tried the plugin in my local testing example. I found the layout of the application is a bit odd. After I did a quick comparison on the generated render function feels like the self-closing tag is not being closed properly. I'll put my example up soon so that you can have a look too.

**Comment by lyonlai** [comment]
@posva the login example is up.

**Comment by posva** [comment]
I'm not sure to understand here. I only wanted to fix the package you recommend on the readme because the one currently displayed is an outdated one but we have an official one

**Comment by lyonlai** [comment]
Sure, at the moment I'm having some issue with the official one you recommended. I'll take a look and get back to you.

**Comment by lyonlai** [comment]
@posva sorry to get back to you late. I've found the config for the example to run. I'm gonna merge this now and push the update to the login example.

Thanks for your help

**Pull request merged**
